# Generated by Django 2.0.4 on 2020-04-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': '日记', 'verbose_name_plural': '日记'},
        ),
    ]
