# Generated by Django 2.0.4 on 2020-04-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200412_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '总类',
                'verbose_name_plural': '总类',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='general_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.General_cate', verbose_name='总类'),
        ),
    ]
